# config file
output_prefix: gene_of_interest
output_path: ./test_output/
rng_seed: 42
wt_seq: ./test_data/gene.gb
vector_seq: ./test_data/gene.gb
homology_length: 20
max_oligo_length: 60
fwd_primer_melt_temp: 50
rev_primer_melt_temp: 55
mutagenesis_type: missense # saturation
variant_windows:
    - gene_1-1
    - gene_1-2
    - gene_1-3
    - gene_1-4
    - gene_1-5
    - gene_2-1
    - gene_2-2
    - gene_2-3
    - gene_3-1
    - gene_3-2
    - gene_4-1
    - gene_4-2
    - gene_4-3
    - gene_4-4
    - gene_4-5
synonymous_variant_rate: .05 # percent of synonymous variants
remove_stop_variant_rate: 1 # do not include stop codons
codon_table: Standard
